### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Seb-33** [beatcracker/Powershell-Misc#3]
Hello,

Thanks for your job ! :)

I got a trouble with your script :(
Some prerequisite to launch the script ? 
I'm on 2012 R2 / domain admin account /elevated powershell prompt

```

PS C:\Users\Administrator> C:\Users\Administrator\Desktop\GMSA.ps1
Use-ServiceAccount : {Access Denied}
A process has requested access to an object, but has not been granted those access rights.
At C:\Users\Administrator\Desktop\GMSA.ps1:306 char:1
+ Use-ServiceAccount -AccountName 'GMSA' -Add
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Use-ServiceAccount


```

**Comment by beatcracker** [comment]
Hi there, thanks!

No prerequisites, it should work out of the box. I've never had issues like this, but quick search shows that it could happen due to some updates missing:

- [NTLM authentication fails with 0xC0000022 error for Windows Server 2012, Windows 8.1, and Windows Server 2012 R2 after update is applied](https://support.microsoft.com/en-us/help/3195799/ntlm-authentication-fails-with-0xc0000022-error-for-windows-server-201)

Could it be your case?

**Comment by Seb-33** [comment]
Hey,
Finally find the answer :
http://portal.sivarajan.com/2014/12/group-managed-service-account-gmsa.html

Set-ADServiceAccount -Identity GMSA -PrincipalsAllowedToRetrieveManagedPassword serverName$
Solved the issue

Script Work with no problem

Thanks again
